# Bakes every gif in assets/gifs into nvim/lua/config/catgif_frames.lua as
# pixel-level palette-indexed frames. PowerShell 5.1 compatible; output is pure ASCII.
param(
  [string]$GifDir = (Join-Path $PSScriptRoot '..\assets\gifs'),
  [string]$Out = (Join-Path $PSScriptRoot '..\nvim\lua\config\catgif_frames.lua')
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

if (-not [System.IO.Path]::IsPathRooted($GifDir)) { $GifDir = Join-Path (Get-Location).Path $GifDir }
if (-not [System.IO.Path]::IsPathRooted($Out)) { $Out = Join-Path (Get-Location).Path $Out }
$GifDir = [System.IO.Path]::GetFullPath($GifDir)
$Out = [System.IO.Path]::GetFullPath($Out)

$gifFiles = @(Get-ChildItem -Path $GifDir -Filter *.gif | Sort-Object Name)
if ($gifFiles.Count -eq 0) { throw "no .gif files found in $GifDir" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('-- Generated by scripts/generate-catgif.ps1 from assets/gifs/. Do not edit by hand.')
[void]$sb.AppendLine('return {')
[void]$sb.AppendLine('  gifs = {')

foreach ($file in $gifFiles) {
  $img = [System.Drawing.Image]::FromFile($file.FullName)
  try {
    $dim = New-Object System.Drawing.Imaging.FrameDimension($img.FrameDimensionsList[0])
    $frameCount = $img.GetFrameCount($dim)
    $w = $img.Width
    $h = $img.Height

    $delayBytes = $null
    try { $delayBytes = $img.GetPropertyItem(0x5100).Value } catch { }
    $delays = @()
    for ($f = 0; $f -lt $frameCount; $f++) {
      $ms = 200
      if ($null -ne $delayBytes -and $delayBytes.Length -ge (4 * $f + 4)) {
        $ms = [int]([BitConverter]::ToUInt32($delayBytes, 4 * $f)) * 10
      }
      if ($ms -le 10) { $ms = 200 }
      $delays += $ms
    }

    # palette index 1 is always the transparent entry
    $palette = New-Object System.Collections.Specialized.OrderedDictionary
    $palette.Add('', 1)
    $frameGrids = @()
    for ($f = 0; $f -lt $frameCount; $f++) {
      [void]$img.SelectActiveFrame($dim, $f)
      # Bitmap copy returns GDI+'s composited 32bpp view of the frame
      $bmp = New-Object System.Drawing.Bitmap($img)
      try {
        $rows = @()
        for ($y = 0; $y -lt $h; $y++) {
          $cells = New-Object System.Collections.Generic.List[string]
          for ($x = 0; $x -lt $w; $x++) {
            $p = $bmp.GetPixel($x, $y)
            if ($p.A -lt 128) { $key = '' }
            else { $key = ('{0:x2}{1:x2}{2:x2}' -f $p.R, $p.G, $p.B) }
            if (-not $palette.Contains($key)) { $palette.Add($key, ($palette.Count + 1)) }
            $cells.Add([string]$palette[$key])
          }
          $rows += ,($cells -join ',')
        }
        $frameGrids += ,$rows
      }
      finally { $bmp.Dispose() }
    }

    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name) -replace "[^A-Za-z0-9_-]", ''
    $palItems = @()
    foreach ($k in $palette.Keys) { $palItems += ("'" + $k + "'") }

    [void]$sb.AppendLine('    {')
    [void]$sb.AppendLine(("      name = '{0}', width = {1}, height = {2}," -f $name, $w, $h))
    [void]$sb.AppendLine(('      delays = { ' + ($delays -join ', ') + ' },'))
    [void]$sb.AppendLine(('      palette = { ' + ($palItems -join ', ') + ' },'))
    [void]$sb.AppendLine('      frames = {')
    foreach ($rows in $frameGrids) {
      [void]$sb.AppendLine('        {')
      foreach ($r in $rows) {
        [void]$sb.AppendLine('          { ' + $r + ' },')
      }
      [void]$sb.AppendLine('        },')
    }
    [void]$sb.AppendLine('      },')
    [void]$sb.AppendLine('    },')
  }
  finally { $img.Dispose() }
}

[void]$sb.AppendLine('  },')
[void]$sb.AppendLine('}')

[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.Encoding]::ASCII)
Write-Host ("wrote {0} ({1} gif(s))" -f $Out, $gifFiles.Count)
